name: PR AI Review
 
on:
  pull_request:
    types: [opened, synchronize]
 
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all branches
        run: git fetch --all
      - name: Call GitHub Model to Review PR Changes
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
    
          git fetch --unshallow || true
          git fetch origin master

          DIFF=$(git diff origin/master...HEAD -- '*.java' | head -c 8000)

 
          PROMPT="The following is a Git diff between two versions of a Java file in a GitHub pull request. Summarize what has changed in terms of logic, methods, or classes. Highlight key differences:\n\n$DIFF"

     
          PAYLOAD=$(jq -n --arg diff "$PROMPT" '{
          "model": "openai/gpt-4o",
          "messages": [
           {
          "role": "user",
          "content": $diff
           }
           ]
           }')

           RESPONSE=$(curl -s https://models.github.ai/inference/chat/completions \
           -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "Content-Type: application/json" \
           -d "$PAYLOAD" | jq -r '.choices[0].message.content')

 
           echo "AI Response:"
           echo "$RESPONSE"

 
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr comment "$PR_NUMBER" --body "$RESPONSE"
