name: AI Java Diff Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  models: read

jobs:
  java-diff-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Base Branch
        run: git fetch origin master

      - name: Ensure Base Exists for Comparison
        run: |
         git fetch --unshallow || true
         git fetch origin master
         git merge-base origin/master HEAD || git merge --allow-unrelated-histories -m "Temporary merge" origin/master || true


      - name: Get Java File Diff
        id: get_diff
        run: |
          DIFF=$(git diff origin/master...HEAD -- '*.java' | head -c 7000)
          if [ -z "$DIFF" ]; then
            echo "No Java changes detected"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "$DIFF" > diff.txt
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Call GitHub AI
        if: steps.get_diff.outputs.skip != 'true'
        id: ai
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROMPT="Summarize the differences in the following Java code diff only. Be clear and concise:\n\n$(cat diff.txt)"

          PAYLOAD=$(jq -n --arg content "$PROMPT" '{
            "model": "openai/gpt-4o",
            "messages": [{"role": "user", "content": $content}]
          }')

          RESPONSE=$(curl -s https://models.github.ai/inference/chat/completions \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")

          echo "$RESPONSE" > raw_response.json

          CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // empty')
          if [ -z "$CONTENT" ]; then
            echo "No response from model."
            CONTENT="⚠️ GitHub AI model did not return a summary."
          fi

          echo "$CONTENT" > response.txt

      - name: Comment on PR
        if: steps.get_diff.outputs.skip != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr comment "$PR_NUMBER" --body "$(cat response.txt)"
